### ISSUE TITLE
'Learning' plugin should trigger if bot is PMed

### ISSUE THREAD

**Issue by pfaffle** [pfaffle/Rawrbot#15]
If a user sends a private message to the bot, it should default to returning 'Learning' data to the user, unless the bot's prefix is detected.

For example, desired behavior would be (In a PM window with the bot):
```
<user> foo
<bot> foo is bar.
<user> !ldap bob
<bot> Performing LDAP search on bob...
...
```

**Comment by eyayron** [comment]
On lines 56-7:

    elsif (m.message.match(/^#{m.bot.nick}[:,-]? (.+)/i))
      teach(m, $1)

Can this be solved with making m.bot.nick optional with "?"

**Comment by pfaffle** [comment]
Not just that on its own, because then the plugin would trigger on any message in any channel. It'll also need to check that it's a PM, at least.
